# PyChain Ledger
###################
# This Streamlit-interface app is a simple proof-of-work blockchain that records basic
# transaction data (sender, receiver, amount, timestamp).
# The interface has a sidebar that allows toggling of the nonce size / mining difficulty,
# and a blockchain validator. 

# Imports
import streamlit as st
from dataclasses import dataclass
from typing import Any, List
import datetime as datetime
import pandas as pd
import hashlib


# Create a 'Record' data class that consists of the `sender`, `receiver`, and `amount` attributes.

@dataclass
class Record:
    sender: str
    receiver: str
    amount: float


# Create a 'Block' data class that will serve as the data-blocks of the blockchain.
# The 'Record' class above will be used within this 'Block' dataclass.

@dataclass
class Block:

    record: Record
    creator_id: int
    prev_hash: str = "0"
    timestamp: str = datetime.datetime.utcnow().strftime("%H:%M:%S")
    nonce: int = 0

    def hash_block(self):
        sha = hashlib.sha256()

        record = str(self.record).encode()
        sha.update(record)

        creator_id = str(self.creator_id).encode()
        sha.update(creator_id)

        timestamp = str(self.timestamp).encode()
        sha.update(timestamp)

        prev_hash = str(self.prev_hash).encode()
        sha.update(prev_hash)

        nonce = str(self.nonce).encode()
        sha.update(nonce)

        return sha.hexdigest()

# Create a dataclass 'Pychain' which will serve as the class for the blockchain instance,
# by attribute of 'chain' which is a list of [Block]s.
# The 'difficulty' attribute is arbitrarily set to 4, but can be adjusted in the user interface. 
# The difficulty is the amount of '0's that the block's hash must start with, generated by nonce iteration.

@dataclass
class PyChain:
    chain: List[Block]
    difficulty: int = 4

    def proof_of_work(self, block):

        calculated_hash = block.hash_block()

        num_of_zeros = "0" * self.difficulty

        while not calculated_hash.startswith(num_of_zeros):

            block.nonce += 1

            calculated_hash = block.hash_block()

        print("Wining Hash", calculated_hash)
        return block

    def add_block(self, candidate_block):
        block = self.proof_of_work(candidate_block)
        self.chain += [block]

    def is_valid(self):
        block_hash = self.chain[0].hash_block()

        for block in self.chain[1:]:
            if block_hash != block.prev_hash:
                print("Blockchain is invalid!")
                return False

            block_hash = block.hash_block()

        msg = "Blockchain is Valid"
        return msg
        

################################################################################
# Streamlit Code

# Add the cache decorator for Streamlit. This allows the ledger to remember past entries and continue adding new data.

@st.cache(allow_output_mutation=True)
def setup():
    print("Initializing Chain")
    return PyChain([Block("Genesis", 0)])


st.markdown("# PyChain")
st.markdown("## Store a Transaction Record in the PyChain")

pychain = setup()

# Add Relevant User Inputs to the Streamlit Interface

# Add an input area where you can get a value for `sender` from the user.
sender = st.text_input("Sender")

# Add an input area where you can get a value for `receiver` from the user.
receiver = st.text_input("Receiver")

# Add an input area where you can get a value for `amount` from the user.
amount = st.text_input("Amount")

# Add a button that creates a new Block containing the user input
if st.button("Add Block"):
    prev_block = pychain.chain[-1]
    prev_block_hash = prev_block.hash_block()

    new_block = Block(
        record = Record(sender=sender, receiver=receiver, amount=amount),
        creator_id = 42,
        prev_hash = prev_block_hash
    )

    pychain.add_block(new_block)
    st.balloons()


st.markdown("## The PyChain Ledger")

pd.options.display.max_colwidth = None

pychain_df = pd.DataFrame(pychain.chain).astype(str)
st.write(pychain_df)

difficulty = st.sidebar.slider("Block Difficulty", 1, 5, 2)
pychain.difficulty = difficulty

st.sidebar.write("# Block Inspector")
selected_block = st.sidebar.selectbox(
    "Which block would you like to see?", pychain_df.index
)

st.sidebar.write(pychain.chain[selected_block])

if st.button("Validate Chain"):
    st.write(pychain.is_valid())

